# parameters:
#   file_content:
#     type: string
#     description: The contents of the file /tmp/file

# resources:
#   boot_config:
#     type: OS::Heat::CloudConfig
#     properties:
#       cloud_config:
#         write_files:
#         - path: /tmp/file
#           content: {get_param: file_content}

#   server_with_cloud_config:
#     type: OS::Nova::Server
#     properties:
#       # flavor, image etc
#       user_data_format: SOFTWARE_CONFIG
#       user_data: {get_resource: boot_config}
heat_template_version: 2018-03-02
description: This template is used to specify boot-time cloud-init configuration.
# parameters:
#   key:
#     type: string
#     default: project_keys
#   flavor:
#     type: string
#   image:
#     type: string
#     default: MU-Ubuntu-16.04-Xenial-64-bit

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: web_server_security_group
      rules:
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22

  wordpress_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: db_name
        - name: db_user
        - name: db_password
        - name: db_ipaddr
      group: script
      config: { get_file: wp_install.sh }

  db_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: db_rootpassword
        - name: db_name
        - name: db_user
        - name: db_password
      group: script
      config: { get_file: db_install.sh }

  mysql_root_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits
 
  database_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  dbms_address:
    type: string
    label: IP address for DBMS.
    default: '<some IP>'

